stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - $RAILS_DEPLOY_PATH/bin/build.sh
  artifacts:
    paths:
      - vendor/bundle/
      - .bundle/

test_job:
  stage: test
  script:
    - $RAILS_DEPLOY_PATH/bin/test.sh

deploy_dev:
  environment:
    name: development
    url: https://rdr-dev.lib.duke.edu/
  stage: deploy
  script:
    - $RAILS_DEPLOY_PATH/bin/deploy.sh
  after_script:
    - $RAILS_DEPLOY_PATH/bin/after_deploy.sh
  only:
    - develop
    - gitlab-ci
    - /^hotfix-/
  tags:
    - development

deploy_pre:
  environment:
    name: staging
    url: https://rdr-pre.lib.duke.edu/
  stage: deploy
  when: manual
  script:
    - $RAILS_DEPLOY_PATH/bin/deploy.sh
  after_script:
    - $RAILS_DEPLOY_PATH/bin/after_deploy.sh
  only:
    - tags
  tags:
    - staging

deploy_prod:
  environment:
    name: production
    url: https://research.repository.duke.edu/
  stage: deploy
  when: manual
  script:
    - $RAILS_DEPLOY_PATH/bin/deploy.sh
  after_script:
    - $RAILS_DEPLOY_PATH/bin/after_deploy.sh
  only:
    - /^v\d+\.\d+\.\d+$/
  tags:
    - production
