include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  ENVIRONMENT_IMAGE: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest

build_job:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $BUILD_IMAGE
    - docker push $BUILD_IMAGE

test_job:
  stage: test

.deploy_job: &deploy_def
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $ENVIRONMENT_IMAGE
    - docker push $ENVIRONMENT_IMAGE
  after_script:
    - sudo /usr/bin/systemctl restart docker-compose@rdr

deploy_dev:
  <<: *deploy_def
  environment:
    name: development
    url: https://rdr-dev.lib.duke.edu/
  only:
    - develop
    - /^hotfix-/
  tags:
    - development
    - docker

deploy_pre:
  <<: *deploy_def
  environment:
    name: staging
    url: https://rdr-pre.lib.duke.edu/
  when: manual
  only:
    - tags
    - /^hotfix-/
  tags:
    - docker
    - staging

deploy_prod:
  <<: *deploy_def
  environment:
    name: production
    url: https://research.repository.duke.edu/
  when: manual
  only:
    - /^v\d+\.\d+\.\d+$/
  tags:
    - docker
    - production
