language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
  - redis-server
before_script:
  - "cp .rspec.travis .rspec"
  - "cp config/role_map.yml.sample config/role_map.yml"
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database travis_ci_test;' -U postgres"
script: "bundle exec rake ci"
jdk:
  - oraclejdk8
