version: '3'

volumes:
  solr:
  pg_data:
  fcrepo:

services:
  app:
    image: rdr
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
      - fcrepo
    environment:
      POSTGRESQL_HOST: db
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:3000"]

  queues:
    image: rdr
    depends_on:
      - redis
    environment:
      POSTGRESQL_HOST: db
    command: ["bundle", "exec", "resque-pool", "-d", "--single-process-group"]

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra

  solr:
    image: solr:7.1.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
    # ports:
    #   - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hydra

  redis:
    image: redis

  fcrepo:
    image: nulib/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data
    # ports:
    #   - "8080:8080"
