version: '3'

volumes:
  solr:
  pg_data:
  fcrepo:

services:
  app:
    image: rdr
    build:
      context: .
    volumes:
      - .:/APPROOT
    ports:
      - "3000:3000"
    environment:
      SOLR_BASE_URL: http://solr:8983/solr
      FCREPO_URL: http://fcrepo:8080/rest
      DATABASE_URL: postgresql://hydra:hydra@db/
    depends_on:
      - db
      - solr
      - fcrepo
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:3000"]

  queues:
    image: rdr
    depends_on:
      - redis
    volumes:
      - .:/APPROOT
    environment:
      SOLR_BASE_URL: http://solr:8983/solr
      FCREPO_URL: http://fcrepo:8080/rest
      DATABASE_URL: postgresql://hydra:hydra@db/
    command: ["bundle", "exec", "resque-pool", "-d", "--single-process-group"]

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra

  solr:
    image: solr:7.1.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/myconfig
      - ./solr/docker:/docker-entrypoint-initdb.d

  redis:
    image: redis

  fcrepo:
    image: nulib/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data
