version: '3.7'

volumes:
  solr:
  pg_data:
  fcrepo:

services:
  app:
    image: rdr
    build:
      context: .
    volumes:
      - .:/APPROOT
    ports:
      - "3000:3000"
    entrypoint: docker-entrypoint-app.sh
    env_file: docker-rails.env
    depends_on:
      - db
      - solr
      - fcrepo
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:3000", "--pidfile", "/var/run/puma.pid"]

  admin:
    image: rdr
    volumes:
      - .:/APPROOT
    env_file: docker-rails.env

  queues:
    image: rdr
    depends_on:
      - app
      - redis
    volumes:
      - .:/APPROOT
    env_file: docker-rails.env
    environment:
      QUEUE: "*"
    entrypoint: docker-entrypoint-resque.sh
    command: ["bundle", "exec", "rails", "resque:work"]

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra

  solr:
    image: solr:7.1.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/myconfig
      - ./solr/docker:/docker-entrypoint-initdb.d

  redis:
    image: redis

  fcrepo:
    image: nulib/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data
