development:
  adapter: solr
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || 'http://localhost:8983/solr/hydra-development' %>

test:
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8985/solr/hydra-test' %>

production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
