default: &default
  adapter: postgresql
  host: localhost
  encoding: UTF8
  username: hydra
  password: hydra

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  adapter: postgresql
  database: hyrax
