docker: &docker
  adapter: postgresql

development:
  <<: *docker
  database: rdr_development

test:
  <<: *docker
  database: rdr_test

production:
  adapter: postgresql
  encoding: UTF8
  database: <%= ENV['DB_DATABASE'] %>
  pool: <%= ENV['DB_POOL'] || '5' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  url: postgresql://localhost/
