default: &default
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8080/rest

development:
  <<: *default
  # user: fedoraAdmin
  # password: fedoraAdmin
  # url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  base_path: /dev

test:
  <<: *default
  # user: fedoraAdmin
  # password: fedoraAdmin
  # url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test

production:
  user: <%= ENV['FCREPO_USERNAME'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: <%= ENV['FCREPO_BASE_PATH'] %>
