development:
  user: fedoraAdmin
  password: <%= ENV['FCREPO_ADMIN_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: <%= ENV['FCREPO_ADMIN_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /test
production:
  user: fedoraAdmin
  password: <%= ENV['FCREPO_ADMIN_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: /prod
