docker: &docker
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL'] %>

development:
  <<: *docker
  base_path: /dev

test:
  <<: *docker
  base_path: /test

production:
  user: <%= ENV['FCREPO_USERNAME'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: <%= ENV['FCREPO_BASE_PATH'] %>
