default: &default
  user: fedoraAdmin
  password: fedoraAdmin

development:
  <<: *default
  url: <%= ENV['FCREPO_URL'] || 'http://localhost:8984/rest' %>
  base_path: /dev

test:
  <<: *default
  url: <%= ENV['FCREPO_URL'] || 'http://localhost:8986/rest' %>
  base_path: /test

production:
  user: <%= ENV['FCREPO_USERNAME'] %>
  password: <%= ENV['FCREPO_PASSWORD'] %>
  url: <%= ENV['FCREPO_URL'] %>
  base_path: <%= ENV['FCREPO_BASE_PATH'] %>
