default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  toolbar1: styleselect | bold italic | numlist bullist | link | undo redo | table hr | image | code |
  plugins:
    - lists
    - link
    - table
    - image
    - hr
    - code
custom:
  <<: *default
