# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior

  property :ark,
           predicate: ::RDF::URI.new("http://repository.lib.duke.edu/vocab/asset/ark"),
           multiple: false do |index|
    index.as :stored_sortable
  end

  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata

  after_create :mint_ark_for_collection

  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  def mint_ark_for_collection
    MintPublishArkJob.perform_later(id)
  end
end
